name: CI
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps --cache-min=9999 --no-audit --progress=false
      - name: Install Cypress system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Check linter
        run: npm run lint
      - name: Check unit tests
        run: npm run test:unit
      - name: Check e2e tests
        run: npm run test:e2e:headless
      - name: Build project
        run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      # - name: Check bundle size
      #   run: npm run bundlesize
